name: pollution-ml
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - geopandas
  - jupyterlab
  - seaborn        # Advanced visualization
  - statsmodels    # Time series analysis
  - pip
  - pip:
      - pykrige
      - scikit-gstat
      - shapely
      - xgboost
      - lightgbm
      - folium
      - ipyleaflet
      - mlflow       # Experiment tracking
      - shap         # Model interpretability
      - dask         # Scalable computation

