name: pollution-ml
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - geopandas
  - jupyterlab
  - pip
  - pip:
      - pykrige
      - scikit-gstat
      - shapely
      - xgboost
      - lightgbm
      - folium
      - ipyleaflet
